### ISSUE TITLE
Poor documentation

### ISSUE THREAD

**Issue by alayoli** [Konshin/EZJson#1]
Hi there!

I just started learning swift and looking for a tiny json library. The build time is really critical for me. Your library looks nice but it has no documentation. Could you please add documentation on English language.

Thanks in advance!

Alay

**Comment by Konshin** [comment]
Hi Alay!

I am glad that you noticed at my library. In the near future, I promise to document it.

**Comment by alayoli** [comment]
Looks like no one gives a shit about this lib. Good luck in hacking swift!
